package com.springdata.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.springdata.service.GeneratedDataService;

import lombok.RequiredArgsConstructor;

@Controller
@RequestMapping("auto-gereted")
@RequiredArgsConstructor
public class ControllerAutoGereted {
	
	private final GeneratedDataService generatedDataService;
	
	@PostMapping("/cargos")
	public ResponseEntity<?> gerarCargos(@RequestParam(required = true, name = "qtd") Integer qtd){
				
		return ResponseEntity.ok(generatedDataService.autoGeneratedCargos(qtd));
		
	}
	
	@PostMapping("/unid-trabalho")
	public ResponseEntity<?> gerarUnidTrabalho(@RequestParam(required = true, name = "qtd") Integer qtd){
				
		return ResponseEntity.ok(generatedDataService.autoGeneratedUnidTrabalho(qtd));
		
	}
	
	@PostMapping("/funcionarios")
	public ResponseEntity<?> gerarFuncionarios(@RequestParam(required = true, name = "qtd") Integer qtd){
				
		return ResponseEntity.ok(generatedDataService.autoGeneratedFuncionario(qtd));
		
	}

}
